spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ppm?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa.hibernate.ddl-auto: update
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false
DoctorApi.url: http://localhost:8080
NurseApi.url: http://localhost:7070
AdminApi.url: http://localhost:6060
server:
  port: 9090